config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  namespace :api do
  	namespace :v1 do
    	resources :exercises
    	resources :reviews, only: [:new, :create]
    end
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	has_many :reviews, dependent: :destroy

	CATEGORIES = ['weights', 'cardio', 'flexibility', 'coordination', 'bodyweight']
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :exercise
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
	respond_to :json
end

app/controllers/api/v1/exercises_controller.rb
class Api::V1::ExercisesController < Api::V1::BaseController
	def index
		respond_with Exercise.all
	end

	def create
		respond_with :api, :v1, Exercise.create(exercise_params)
	end

	def update
		exercise = Exercise.find(params[:id])
		exercise.update_attributes(exercise_params)
		respond_with exercise, json: exercise
	end

	def destroy
		respond_with Exercise.destroy(params[:id])
	end

	private

	def exercise_params 
		params.require(:exercise).permit(:category, :name, :description, :rating)
	end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < Api::V1::BaseController
	def new
		@exercise = Exercise.find(params[:exercise_id])
		@review = Review.new
	end

	def create
		@review = Review.create(review_params)
		if @review.save
			redirect_to exercises_path
		else
			flash[:alert] = "Review couldn't be saved"
		end
	end

	private

	def review_params
		params.require(:review).permit(:name, :comments, :rating, :exercise_id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@exercise = Exercise.find(params[:exercise_id])
		@review = Review.new
	end

	def create
		@review = Review.create(review_params)
		if @review.save
			redirect_to exercises_path
		else
			flash[:alert] = "Review couldn't be saved"
		end
	end

	private

	def review_params
		params.require(:review).permit(:name, :comments, :rating, :exercise_id)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<%= link_to "New", new_exercise_path %>
<% @exercises.each do |exercise| %>
	<div style="border: 2px solid #aaaaaa; border-radius: 3px; width: 400px; padding: 15px; margin-top: 20px;">
		<h3 style="margin-top: 0;"><%= exercise.name %></h3>
		<h5>Category: <%= exercise.category %></h5>
		Description: <p><%= exercise.description %></p>
		<br>
		<span>Rating: <%= exercise.rating %></span>
		<br>
		<br>
		<h5>Reviews (<%= link_to "Add Review", new_review_path(exercise_id: exercise.id) %>)</h5>

		<ul style="list-style-type: none;">
			<% exercise.reviews.each do |review| %>
				<li style="border-bottom: 1px solid #bbbbdd; padding-top: 10px;">
					<strong><%= review.rating %></strong> - <em>by <%= review.name %></em>
					<br>
					<p><%= review.comments %></p>
				</li>
			<% end %>
		</ul>

	</div>
<% end %>

app/views/exercises/new.html.erb
<h1>New Exercise</h2>
<%= simple_form_for @exercise do |f| %>
	<%= f.input :name %><br>
	<%= f.input :category %><br>
	<%= f.input :description %><br>
	<%= f.input :rating %>
	<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reactant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style>
	body {
		font-family: Arial, sans-serif;
	}
  </style>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/new.html.erb
<h1>Add review</h1>

<div style="border: 2px solid #aaaaaa; border-radius: 3px; width: 400px; padding: 15px;">
	<h3 style="margin-top: 0;"><%= @exercise.name %></h3>
	<h6>Category: <%= @exercise.category %></h6>
	Description: <p><%= @exercise.description %></p>
	<br>
	<span>Rating: <%= @exercise.rating %></span>
</div>

<%= simple_form_for @review do |f| %>
	<%= f.input :name %>
	<%= f.input :comments %>
	<%= f.input :rating %>
	<%= f.hidden_field :exercise_id, value: @exercise.id %>
	<br>
	<br>
	<%= f.button :submit %>
<% end %>